### PR TITLE
update regex to accomodate the new format for playlists while maintai…

### PR DESCRIPTION
**Pull request by stvedt**
…ning backwards compat for the old structure

### CODE REVIEW

**Comment by stvedt** [comment]
@garetmckinley Thanks for merging. Will you create a release so this update is available through package managers?

**Comment by ariamckinley** [comment]
Yes :) currently doing some maintenance on another repo, I'll switch up and cut a release later this evening. Thanks for the PR :trophy:

**Comment by ariamckinley** [comment]
@stvedt just released v2.1.0, sorry for the delay.

**Comment by stvedt** [comment]
Thanks so much!!

**Comment by stvedt** [comment]
@garetmckinley Not sure if I'm missing something but the latest release on npm does not include the latest source. The tag on GH certainly does but https://registry.npmjs.org/gatsby-remark-embed-spotify/-/gatsby-remark-embed-spotify-2.1.0.tgz doesn't appear to have the new regex. Please advise.

**Comment by ariamckinley** [comment]
ah, I think I see what happened. It looks like you modified the regex of the compiled `index.js` file and not `src/index.js`. So when I published it, the build step must have overridden the changes. If you wanna make a new PR, feel free too. Otherwise I'll be able to make the change myself later on tonight :ok_hand:

**Comment by stvedt** [comment]
Oh, snap. That would do it. I'll submit another PR shortly!

**Pull request merged**
